import type { Metadata } from 'next'
import './globals.css'
import { montserrat } from '@/fonts'

export const metadata: Metadata = {
  title: 'Skooly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={`${montserrat.className} bg-primary h-full`}>{children}</body>
    </html>
  )
}
